apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata:
  name: "ubuntu18.04-persistent"
spec:
  app: ubuntu18x
  roles:
  - id: vanilla_ubuntu
    members: 1
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
    storage:
      size: "40Gi"
