apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubedirectorapps.kubedirector.hpe.com
spec:
  group: kubedirector.hpe.com
  preserveUnknownFields: false
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required: [apiVersion, kind, metadata, spec]
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            required: [label, distroID, version, roles, config, configSchemaVersion]
            properties:
              label:
                type: object
                required: [name]
                properties:
                  name:
                    type: string
                    minLength: 1
                  description:
                    type: string
              distroID:
                type: string
                minLength: 1
              version:
                type: string
                minLength: 1
              configSchemaVersion:
                type: integer
                minimum: 7
              defaultImageRepoTag:
                type: string
                minLength: 1
              defaultConfigPackage:
                type: object
                nullable: true
                required: [packageURL]
                properties:
                  packageURL:
                    type: string
                    pattern: '^(file|https?)://.+\.tgz$'
              services:
                type: array
                items:
                  type: object
                  required: [id]
                  properties:
                    id:
                      type: string
                      minLength: 1
                      maxLength: 15
                      pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                    label:
                      type: object
                      nullable: true
                      required: [name]
                      properties:
                        name:
                          type: string
                          minLength: 1
                        description:
                          type: string
                    endpoint:
                      type: object
                      nullable: true
                      required: [port]
                      properties:
                        port:
                          type: integer
                          minimum: 1
                          maximum: 65535
                        urlScheme:
                          type: string
                          minLength: 1
                          maxLength: 15
                          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                        path:
                          type: string
                        isDashboard:
                          type: boolean
              roles:
                type: array
                items:
                  type: object
                  required: [id, cardinality]
                  properties:
                    id:
                      type: string
                      minLength: 1
                      maxLength: 63
                      pattern: '^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?$'
                    cardinality:
                      type: string
                      pattern: '^\d+\+?$'
                    imageRepoTag:
                      type: string
                      minLength: 1
                    configPackage:
                      type: object
                      nullable: true
                      required: [packageURL]
                      properties:
                        packageURL:
                          type: string
                          pattern: '^(file|https?)://.+\.tgz$'
                    persistDirs:
                      type: array
                      items:
                        type: string
                        pattern: '^/.*[^/]$'
                    minResources:
                      type: object
                      nullable: true
                      properties:
                        memory:
                          type: string
                          pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                        cpu:
                          type: string
                          pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                        ephemeral-storage:
                          type: string
                          pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                        nvidia.com/gpu:
                          type: string
                          pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                        amd.com/gpu:
                          type: string
                          pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
              config:
                type: object
                required: [selectedRoles, roleServices]
                properties:
                  configMeta:
                    type: object
                    nullable: true
                  selectedRoles:
                    type: array
                    items:
                      type: string
                      minLength: 1
                  roleServices:
                    type: array
                    items:
                      type: object
                      required: [roleID, serviceIDs]
                      properties:
                        roleID:
                          type: string
                          minLength: 1
                          maxLength: 63
                          pattern: '^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?$'
                        serviceIDs:
                          type: array
                          items:
                            type: string
                            minLength: 1
                            maxLength: 15
                            pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
              defaultPersistDirs:
                type: array
                items:
                  type: string
                  pattern: '^/.*[^/]$'
              capabilities:
                type: array
                items:
                  type: string
                  minLength: 1
              systemdRequired:
                type: boolean
  - name: v1beta2
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        required: [apiVersion, kind, metadata, spec]
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            required: [label, distroID, version, roles, config, configSchemaVersion]
            properties:
              label:
                type: object
                required: [name]
                properties:
                  name:
                    type: string
                    minLength: 1
                  description:
                    type: string
              distroID:
                type: string
                minLength: 1
              version:
                type: string
                minLength: 1
              configSchemaVersion:
                type: integer
                minimum: 7
              defaultImageRepoTag:
                type: string
                minLength: 1
              defaultConfigPackage:
                type: object
                nullable: true
                required: [packageURL]
                properties:
                  packageURL:
                    type: string
                    pattern: '^(file|https?)://.+\.tgz$'
              services:
                type: array
                items:
                  type: object
                  required: [id]
                  properties:
                    id:
                      type: string
                      minLength: 1
                      maxLength: 15
                      pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                    label:
                      type: object
                      nullable: true
                      required: [name]
                      properties:
                        name:
                          type: string
                          minLength: 1
                        description:
                          type: string
                    endpoint:
                      type: object
                      nullable: true
                      required: [port]
                      properties:
                        port:
                          type: integer
                          minimum: 1
                          maximum: 65535
                        urlScheme:
                          type: string
                          minLength: 1
                          maxLength: 15
                          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                        path:
                          type: string
                        isDashboard:
                          type: boolean
              roles:
                type: array
                items:
                  type: object
                  required: [id, cardinality]
                  properties:
                    id:
                      type: string
                      minLength: 1
                      maxLength: 63
                      pattern: '^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?$'
                    cardinality:
                      type: string
                      pattern: '^\d+\+?$'
                    imageRepoTag:
                      type: string
                      minLength: 1
                    configPackage:
                      type: object
                      nullable: true
                      required: [packageURL]
                      properties:
                        packageURL:
                          type: string
                          pattern: '^(file|https?)://.+\.tgz$'
                    persistDirs:
                      type: array
                      items:
                        type: string
                        pattern: '^/.*[^/]$'
                    eventList:
                      type: array
                      items:
                        type: string
                        pattern: '^configure$|^addnodes$|^delnodes$'
                    minResources:
                      type: object
                      nullable: true
                      properties:
                        memory:
                          type: string
                          pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                        cpu:
                          type: string
                          pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                        ephemeral-storage:
                          type: string
                          pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                        nvidia.com/gpu:
                          type: string
                          pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                        amd.com/gpu:
                          type: string
                          pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
              config:
                type: object
                required: [selectedRoles, roleServices]
                properties:
                  configMeta:
                    type: object
                    nullable: true
                  selectedRoles:
                    type: array
                    items:
                      type: string
                      minLength: 1
                  roleServices:
                    type: array
                    items:
                      type: object
                      required: [roleID, serviceIDs]
                      properties:
                        roleID:
                          type: string
                          minLength: 1
                          maxLength: 63
                          pattern: '^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?$'
                        serviceIDs:
                          type: array
                          items:
                            type: string
                            minLength: 1
                            maxLength: 15
                            pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
              defaultPersistDirs:
                type: array
                items:
                  type: string
                  pattern: '^/.*[^/]$'
              defaultEventList:
                type: array
                items:
                  type: string
                  pattern: '^configure$|^addnodes$|^delnodes$'
              capabilities:
                type: array
                items:
                  type: string
                  minLength: 1
              systemdRequired:
                type: boolean
  conversion:
    strategy: Webhook
    conversionReviewVersions: ["v1beta1", "v1beta2"]
    webhookClientConfig:
        service:
          namespace: default
          name: kubedirector-validator
          path: /crdconvert
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyRENDQWNDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFkTVJzd0dRWURWUVFERXhKb2NHVmoKY0MxMllXeHBaR0YwYjNJdFkyRXdIaGNOTWpBd05UQTRNVGt6TVRNMVdoY05NekF3TlRBMk1Ua3pNVE0xV2pBZApNUnN3R1FZRFZRUURFeEpvY0dWamNDMTJZV3hwWkdGMGIzSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUURSQ3JleTNpckJGalBYSEtEaXM2c3hadW5IN0d1MnVoOEhsd0doKytjM3lPOE8KejlKTHlOK0l3V1hLWG1MMFZzSmpKcGNoVnVWWjBvOEtZTCtoSmdOL3pBemdFV0daTEx1aFB0UVVuZnJwdFZxSwo0aG85WWQ5V1ZFYkUrV255ZnRXUXVjYXZPaTg5cWlydG8vWFhCYW1vUzM1Ris5eGh1SUdONFFKQlNGZ1k1QytVCnJWc0tMbjhZREFnMng2NitQRzg5cUN4MGY5WGxxMVBhZ1B6MVZqVzM1WExheVZvckR2MjluTENDODJhbzNUTlQKV3pXSkZlMzY2OE9LMVZNOStMaWtwbHZEVmJvUDVDdUc1S3c4UFYyekhpSzFuOUlscmNlZWFiUFo0SXdWZHh2dQpPVWIrQm52MStDWXJzdHRmMitiVUtxMUxkYTYxN3VHVDRPSWdPQ1dYQWdNQkFBR2pJekFoTUE0R0ExVWREd0VCCi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDVlpjZWsKcm50bzd5aGdyYU80T05pVnFqK2Ficm1TdUE1LzgwY04wWFBDMm5oMU91dnh6ZW9VSTFGOXRMd1NlMDFwWWp4aApEWml4bFN2cS9YKy9PeGM5V20vQ213NVNKcTJsVjNPQ0wyL29iZmtpeUZpY3RwLzUybGlYWFNVdnRCRFVUNm5yClJpV2YvdktxUGFRT0NNQk9EVW85ZUViSVZ2c1RvNlpDV3dLS3JiaFdqNFNLVWxKbWRQdUhzU21YTXdiclZUd0kKWVNnYjkxNGdXTE50NkVZcUY1QUJ6Z2RJUS9BSTBsbjN6a0laN3M3M1pIZTh4ZTYxd2FBUkFqT1Q1b2FOSjVrWAo3MmNIbWRveWRWVTVlTit5aEovTGtyalNPMlErQ2dwR1RaUE1PUVVqUHI0emh3WGp4MFBMeWM1OS80VEs1OXh1Cks0OVV6UWRGMmxxYU5uVEEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  names:
    kind: KubeDirectorApp
    listKind: KubeDirectorAppList
    plural: kubedirectorapps
    singular: kubedirectorapp
    shortNames:
    - kdapp
  scope: Namespaced